name: CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Testing secrets
      run: |
        echo 'GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}'
        echo 'MY_DEV_SECRET: ${{ secrets.MY_DEV_SECRET }}'
        echo 'MY_PROD_SECRET: ${{ secrets.MY_PROD_SECRET }}'
        echo 'MY_OWN_SECRET: ${{ secrets.MY_OWN_SECRET }}'
