name: CI

on:
  pull_request
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Decrypt large secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: $
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/secrets/my_secret.json
