name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy on production
      run: echo 'Deploying to production using secret ${{ secrets.MY_PROD_SECRET }}'
    - name: Testing secrets
      run: printenv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_DEV_SECRET: ${{ secrets.MY_DEV_SECRET }}
        MY_PROD_SECRET: ${{ secrets.MY_PROD_SECRET }}
