name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy on production
      run: echo 'Deploying to production using secret ${{ secrets.MY_PROD_SECRET }}'
