name: Test

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: List files
      run: ls -latr
    - name: List images
      run: docker images
    - name: Set tag var
      id: vars
      run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)-${GITHUB_SHA}
    - name: Build Docker image
      env:
        TAG: ${{ steps.vars.outputs.docker_tag }}
      run: |
        echo $TAG
        echo ${{ steps.vars.outputs.docker_tag }}
        docker build . --file .github/actions/test/Dockerfile --tag myapp:${{ steps.vars.outputs.docker_tag }}
    - name: List images
      run: docker images
