name: CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Hacking secrets
      run: printenv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MY_DEV_SECRET: ${{ secrets.MY_DEV_SECRET }}
        MY_PROD_SECRET: ${{ secrets.MY_PROD_SECRET }}
