name: Test

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: List files
      run: ls -latr
    - name: List images
      run: docker images
    - name: Build Docker image
      run: docker build . --file .github/actions/test/Dockerfile --tag myapp:$@{{ steps.vars.outputs.docker_tag }}
    - name: List images
      run: docker images
