name: Test

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: List files
      run: ls -latr
    - name: List images
      run: docker images
